name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 저장된 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: 생성된 빌드 파일의 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: 프로젝트를 압축하여 AWS S3에 저장
        run: tar -czvf $GITHUB_SHA.tar.gz project.jar appspec.yml scripts

      - name: AWS 리소스에 접근할 수 있도록 AWS Credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 버킷에 프로젝트 폴더 업로드
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://cicd-server/$GITHUB_SHA.tar.gz

      - name: Code Deploy를 사용하여 EC2에 프로젝트 배포
        run: aws deploy create-deployment 
            --application-name cicd-server
            --deployment-config-name CodeDeployDefault.AllAtOnce 
            --deployment-group-name Production 
            --s3-location bucket=cicd-server,bundleType=tar,key=$GITHUB_SHA.tar.gz